# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # 指定 pnpm 版本，可以根据需要调整
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependency
        run: pnpm install
      - name: Build
        run: pnpm run build
      - run: echo "${{ vars.NPM_PUBLISH }}"
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{vars.NPM_PUBLISH}}